twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    file_name_pattern: '*.twig'
    globals:
        site:
            name: '%app.site.name%'

when@test:
    twig:
        strict_variables: true

